---

- name: Raneto
  hosts: raneto:&web
  roles:

    # Clone Raneto Application Repository
    # You'll want to edit this line with your team's documentation repository
    # The cloned repository lives in the Home Directory
    #
    # We use HTTPS because this is a public repository, as an example
    # You can use SSH-based, including key support, just uncomment the
    # SSH private and public key files and add the appropriate filepaths
    # Make sure you also add the *public* key in the pair to your Git host's
    # Deploy Keys or you will be denied permission to clone.
    # NEVER SHARE YOUR PRIVATE KEY WITH ANYONE
    - role: ryanlelek.git-repo
      git_repo_name:             raneto
      git_repo_url:              https://github.com/gilbitron/Raneto.git
      #git_repo_ssh_private_key: ./keys/id_rsa
      #git_repo_ssh_public_key:  ./keys/id_rsa.pub
      git_repo_command:          npm install

    # Generate the Nginx site configuration
    # Proxy any non-static file request to Node.js
    - role: ryanlelek.site
      become: yes
      site_root: raneto/public
      site_domain: devops.raneto.com
      site_www: false
      site_ssl: false
      site_proxy: nodejs # Enables proxy
      site_proxy_name: raneto
      site_proxy_port: 3000

    # Node Daemon for our Raneto application
    - role: ryanlelek.daemon-nodejs
      become: no
      daemon_name: raneto
      daemon_envvars:
        # Probably a good idea to leave these as-is
        # unless you have a good reason to edit them...
        # You can add new ones though, right below these
        - { key: NODE_ENV, value: PRODUCTION }
        - { key: PORT,     value: 3000 }
