---

# Smooth over Provider differences
- name: Base Setup Among Providers
  hosts: all
  gather_facts: false
  roles:
    - ryanlelek.providers

# Common to every system
# Users, packages, swapfile, etc.
- name: All Systems
  hosts: all
  become: yes
  vars:
    packages_upgrade: true
  roles:
    - role: kamaln7.swapfile
      swapfile_size: 1GB
      swapfile_swappiness: 10
      swapfile_location: /mnt/swapfile
    - ryanlelek.packages
    - ryanlelek.sshd
    - ryanlelek.timezone
    - ryanlelek.logout
    - ryanlelek.reboot
