---

# Smooth over Provider differences
- name: Base Setup Among Providers
  hosts: all
  gather_facts: false
  roles:
    - ryanlelek.providers

# Common to every system
# Users, packages, swapfile, etc.
- name: All Systems
  hosts: all
  become: yes
  vars:
    packages_upgrade: true
  roles:
    - ryanlelek.packages
    - ryanlelek.sshd
    - ryanlelek.timezone
    - ryanlelek.logout
    - role: kamaln7.swapfile
      swapfile_size: 1GB
      swapfile_swappiness: 10
      swapfile_location: /mnt/swapfile
    - ryanlelek.reboot

# Now, we get more specific for what
# we need to do for our web servers
- name: Web Servers
  hosts: web
  become: yes
  gather_facts: true
  roles:

    # Enable Firewall
    # Let in HTTP Traffic
    - role: ryanlelek.firewall
      http_in: true

    # Install Nginx
    - role: ryanlelek.nginx
      # Redirect (301 Permanent) if a domain does not match
      redirect_url: http://www.ansibletutorials.com

    # Install Node.js
    - nodesource.node
