---

################
### SETTINGS ###
################

# Set Time Zone
# - Etc/UTC
# - America/New_York
# - America/Los_Angeles
# echo 'Etc/UTC' | sudo tee /etc/timezone > /dev/null
- name: Update Timezone to Etc/UTC
  copy: content="Etc/UTC\n" dest=/etc/timezone owner=root group=root mode=0644
  become: yes
  register: timezone

- name: Reconfigure Timezone Data
  shell: dpkg-reconfigure -f noninteractive tzdata
  become: yes
  when: timezone.changed

###################
### USER CONFIG ###
###################

- name: Bash Logout Script (Clear History)
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  remote_user: "{{ ansible_ssh_user }}"
  copy: src=bash_logout.secured dest=/home/{{ ansible_ssh_user }}/.bash_logout owner={{ ansible_ssh_user }} mode=0644

########################
### UPGRADE PACKAGES ###
########################

# This will have a conditional shortly to
# ensure it only runs on initial provision
- include: upgrade.yml

########################
### REBOOT IF NEEDED ###
########################

- include: reboot.yml
