---

########################
### UPGRADE PACKAGES ###
########################

# This will have a conditional shortly to
# ensure it only runs on initial provision
- include: upgrade.yml

########################
### REBOOT IF NEEDED ###
########################

- include: reboot.yml
