---
ssh_in:                   true
ssh_out:                  false
http_in:                  false
http_out:                 true
https_in:                 false
https_out:                true
git_out:                  false
git_port:                 9418
papertrail_out:           true
mongodb_in:               false
mongodb_out:              false
mongodb_port:             27017
redis_in:                 false
redis_out:                false
rabbitmq_in:              false
rabbitmq_out:             false
rabbitmq_port:            5672
rabbitmq_management:      false
rabbitmq_management_ip:   127.0.0.1
rabbitmq_management_port: 15672
