---

##################
### SSH CONFIG ###
##################

- name: SSHD Configuration
  become: yes
  copy: src=sshd_config.secured dest=/etc/ssh/sshd_config owner=root group=root mode=0644

- name: Remove Root SSH Configuration
  become: yes
  file: path=/root/.ssh state=absent

- name: Regenerate Missing SSH Keys as Root
  shell: ssh-keygen -A
  become: yes
  register: keygen_result
  # Output: ssh-keygen: generating new host keys: RSA1 ED25519
  changed_when: keygen_result.stdout != ""

# TODO: Disabled handler due to disconnect bug
# https://github.com/ansible/ansible-modules-core/issues/1298
#- name: SSHD Restart
#  become: yes
#  service: name=sshd state=restarted enabled=yes
