---

# The goal of this role is to create
# the main Ansible, give that user sudo
# privileges and then exit. This varies
# from provider to provider, so we handle
# laying this common ground here and normalize

# Vagrant
- include: root.yml
  become: yes
  vars:
    ansible_ssh_user: vagrant
    user_username: vagrant
  when: "'vagrant' in group_names"

# DigitalOcean
- include: digitalocean.yml
  when: "'digitalocean' in group_names"
