---

# Similar Problem
# https://groups.google.com/forum/#!topic/ansible-project/UMtmnBbJ6vk
# http://stackoverflow.com/questions/19642167/ansible-test-if-ssh-login-possible-without-fatal-error

# SSH Host Key Checking
# http://linuxcommando.blogspot.com/2008/10/how-to-disable-ssh-host-key-checking.html

# Usual output when provisioned
# because root SSH login is disabled)
# "Permission denied (publickey)."
# SSH Check Code From: http://unix.stackexchange.com/questions/30140/how-to-check-if-i-can-log-in-to-server-via-ssh
- name: Checking Provisioned Status
  # Alternates
  # {{ ansible_ssh_host }}
  local_action: shell ssh -o BatchMode=yes -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ inventory_hostname }} echo "NEW" || echo "PROVISIONED" 2>&1
  #ignore_errors: True
  changed_when: False
  register: host_provisioned

# Run Root Tasks (if needed)
- include: root.yml
  become: yes
  vars:
    ansible_ssh_user: root
  when: host_provisioned.stdout == "NEW"
