---

- name: Ensure sudo group exists
  group: name=sudo state=present

- name: Ensure User exists
  user: name={{ user_username }} password={{ user_password }} group=sudo generate_ssh_key=yes shell="/bin/bash" state=present

- name: Ensure the ~/.ssh directory exists for the User
  file: path=/home/{{ user_username }}/.ssh state=directory owner={{ user_username }} mode=0700

- name: Upload the local id_rsa.pub key as authorized key
  remote_user: root
  copy: src=~/.ssh/id_rsa.pub dest=/home/{{ user_username }}/.ssh/authorized_keys owner={{ user_username }} group=sudo mode=0600
  when: "'vagrant' not in group_names"
